# Generated by Django 4.1.4 on 2022-12-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='/images/default-profile.PNG', null=True, upload_to='users/profile_pictures'),
        ),
    ]
