# Generated by Django 4.1.4 on 2022-12-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_book_remove_category_category_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Strain',
        ),
    ]
