# Generated by Django 4.1.4 on 2022-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_book_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='cbd',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='dominant_terpene',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='image',
            field=models.ImageField(default=1, upload_to='strain'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strain',
            name='strain_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='thc',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='top_reported_effect',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
