# Generated by Django 4.1.4 on 2022-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_strain_cbd_strain_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
