# Generated by Django 4.1.4 on 2022-12-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_strain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
