# Generated by Django 4.1.4 on 2022-12-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
            preserve_default=False,
        ),
    ]
