# Generated by Django 4.1.4 on 2022-12-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_strain_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_reviews',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
    ]
