# Generated by Django 4.1.4 on 2022-12-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strain',
            old_name='strain_type',
            new_name='type',
        ),
    ]
